### PR TITLE
Made lens optional

### PR DESCRIPTION
**Pull request by ilyakooo0**

### CODE REVIEW

**Comment by ilyakooo0** [comment]
I'm not sure where the nix expression for the library is coming from.

Can someone help me fix CI?

**Comment by Ericson2314** [comment]
@ilyakooo0 I am not super eager about this I must admit. Flags that change the exported interface are not that useful because there is no way to specify downstream whether the dependency needs extra stuff.

**Comment by ilyakooo0** [comment]
Sure 

You can close this PR

**Comment by ilyakooo0** [comment]
It turns out, removing pens from the dependency tree doesn't give a huge improvement in binary size. (That was my motivation for doing this)

**Comment by Ericson2314** [comment]
Ah yes if you are just worried about binary size not build times / frequency of rebuilding, static linking with `--gc-sections` and friends should do just fine.

**Pull request closed without merging**
